# Generated by Django 3.1.4 on 2020-12-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addItem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
